### PR TITLE
Add support for WSL hosts file

### PR DESCRIPTION
**Pull request by JacobDB**
This change checks if a hosts file exists at `/mnt/c/Windows/System32/drivers/etc/hosts`, and if so, attempts to add or remove the virtual host specified. This makes the script more compatible with Microsoft's Windows Subsystem on Linux.

### CODE REVIEW

**Comment by alanaasmaa** [comment]
+1

**Comment by JacobDB** [comment]
Only issue with this is that it can't actually write to Window's HOSTS file unless you change the permissions on it. I'm told there may be something like `winsudo` in the future to allow this to work properly.

**Comment by RoverWire** [comment]
Interesnting, let me make some test to ensure it does not affect other cases. Great contribution :+1:

**Comment by JacobDB** [comment]
Just adjusted this so that it properly writes a Windows-style line ending in the Windows HOSTS file (before it was working, but would behave weirdly if you opened up HOSTS in Windows)

**Pull request merged**
